---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7.2

  Exclude:
    - 'db/schema.rb'

Rails:
  Enabled: true
